laravel-codedelivery/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix'=>'admin','middleware'=>'auth.checkrole', 'as'=>'admin.'], function() {
    Route::get('categories',['as'=>'categories.index','uses'=>'CategoriesController@index']);
    Route::get('categories/create',['as'=>'categories.create','uses'=>'CategoriesController@create']);
    Route::get('categories/edit/{id}',['as'=>'categories.edit','uses'=>'CategoriesController@edit']);
    Route::post('categories/update/{id}',['as'=>'categories.update','uses'=>'CategoriesController@update']);
    Route::post('categories/store',['as'=>'categories.store','uses'=>'CategoriesController@store']);

    Route::get('products',['as'=>'products.index','uses'=>'ProductsController@index']);
    Route::get('products/create',['as'=>'products.create','uses'=>'ProductsController@create']);
    Route::get('products/edit/{id}',['as'=>'products.edit','uses'=>'ProductsController@edit']);
    Route::post('products/update/{id}',['as'=>'products.update','uses'=>'ProductsController@update']);
    Route::post('products/store',['as'=>'products.store','uses'=>'ProductsController@store']);
    Route::get('products/destroy/{id}',['as'=>'products.destroy','uses'=>'ProductsController@destroy']);

    Route::get('clients',['as'=>'clients.index','uses'=>'ClientsController@index']);
    Route::get('clients/create',['as'=>'clients.create','uses'=>'ClientsController@create']);
    Route::get('clients/edit/{id}',['as'=>'clients.edit','uses'=>'ClientsController@edit']);
    Route::post('clients/update/{id}',['as'=>'clients.update','uses'=>'ClientsController@update']);
    Route::post('clients/store',['as'=>'clients.store','uses'=>'ClientsController@store']);
    Route::get('clients/destroy/{id}',['as'=>'clients.destroy','uses'=>'ClientsController@destroy']);

    Route::get('orders',['as'=>'orders.index','uses'=>'OrdersController@index']);
    Route::get('orders/{id}',['as'=>'orders.edit','uses'=>'OrdersController@edit']);
    Route::post('orders/update/{id}',['as'=>'orders.update','uses'=>'OrdersController@update']);

    Route::get('cupoms',['as'=>'cupoms.index','uses'=>'CupomsController@index']);
    Route::get('cupoms/create',['as'=>'cupoms.create','uses'=>'CupomsController@create']);
    Route::get('cupoms/{id}',['as'=>'cupoms.edit','uses'=>'CupomsController@edit']);
    Route::post('cupoms/update/{id}',['as'=>'cupoms.update','uses'=>'CupomsController@update']);
    Route::post('cupoms/store',['as'=>'cupoms.store','uses'=>'CupomsController@store']);
    Route::get('cupoms/destroy/{id}',['as'=>'cupoms.destroy','uses'=>'CupomsController@destroy']);
});

Route::group(['prefix'=>'customer', 'as'=>'customer.'], function() {

    Route::get('order',['as'=>'order.index', 'uses'=>'CheckoutController@index']);
    Route::get('order/create',['as'=>'order.create','uses'=>'CheckoutController@create']);
    Route::post('order/store',['as'=>'order.store','uses'=>'CheckoutController@store']);



});

laravel-codedelivery/app/Models/Client.php
<?php

namespace CodeDelivery\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Client extends Model implements Transformable
{
    use TransformableTrait;

    protected $fillable = [
        'user_id',
        'phone',
        'address',
        'city',
        'state',
        'zipcode'
    ];

    public function user(){
        return $this->hasOne(User::class,'id', 'user_id');
    }

}

laravel-codedelivery/app/Http/Controllers/ClientsController.php
<?php

namespace CodeDelivery\Http\Controllers;

use CodeDelivery\Http\Requests\AdminClientRequest;

use CodeDelivery\Http\Requests;
use CodeDelivery\Repositories\CategoryRepository;
use CodeDelivery\Repositories\ClientRepository;
use CodeDelivery\Services\ClientService;

class ClientsController extends Controller
{

    /**
     * @var ClientRepository
     */
    private $repository;
    /**
     * @var CategoryRepository
     */
    private $categoryRepository;
    /**
     * @var ClientService
     */
    private $clientService;


    public function __construct(ClientRepository $repository, ClientService $clientService)
    {
        $this->repository = $repository;

        $this->clientService = $clientService;
    }

    public function index()
    {

        $clients = $this->repository->paginate(5);

        return view('admin.clients.index', compact('clients'));

    }

    public function create()
    {
        return view('admin.clients.create', compact('categories'));
    }

    public function store(AdminClientRequest $request)
    {
        $data = $request->all();
        $this->clientService->create($data);

        return redirect()->route('admin.clients.index');
    }

    public function edit($id)
    {

        $client = $this->repository->find($id);

        return view('admin.clients.edit', compact('client', 'categories'));

    }

    public function update(AdminClientRequest $request, $id)
    {

        $data = $request->all();
        $this->clientService->update($data, $id);

        return redirect()->route('admin.clients.index');

    }

    public function destroy($id)
    {
        $this->repository->delete($id);

        return redirect()->route('admin.clients.index');
    }
}

laravel-codedelivery/resources/views/admin/clients/_form.blade.php
<div class="form-group">
    {!! Form::label('Name', 'Nome:') !!}
    {!! Form::text('user[name]', null, ['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('Email', 'Email:') !!}
    {!! Form::text('user[email]', null, ['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('Phone', 'Telefone:') !!}
    {!! Form::text('phone', null, ['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('Address', 'Endereço:') !!}
    {!! Form::textarea('address', null, ['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('City', 'Cidade:') !!}
    {!! Form::text('city', null, ['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('State', 'Estado:') !!}
    {!! Form::text('state', null, ['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('Zipcode', 'Cep:') !!}
    {!! Form::text('zipcode', null, ['class'=>'form-control']) !!}
</div>

laravel-codedelivery/resources/views/admin/clients/create.blade.php
@extends('app')

@section('content')
    <div class="container">
        <h3>Novo Cliente</h3>

        @include('errors._check')

        {!! Form::open(['route'=>'admin.clients.store']) !!}

        @include('admin.clients._form')

        <div class="form-group">
            {!! Form::submit('Criar cliente', ['class'=>'btn btn-primary']) !!}
        </div>

        {!! Form::close() !!}

    </div>
@endsection

laravel-codedelivery/resources/views/admin/clients/edit.blade.php
@extends('app')

@section('content')
    <div class="container">
        <h3>Editando cliente: {{$client->user->name}}</h3>

        @include('errors._check')

        {!! Form::model($client, ['route'=>['admin.clients.update', $client->id]]) !!}

        @include('admin.clients._form')

        <div class="form-group">
            {!! Form::submit('Salvar', ['class'=>'btn btn-primary']) !!}
        </div>

        {!! Form::close() !!}

    </div>
@endsection

laravel-codedelivery/resources/views/admin/clients/index.blade.php
@extends('app')

@section('content')
    <div class="container">
        <h3>Clientes</h3>
        <br>
        <a href="{{ route('admin.clients.create')  }}" class="btn btn-default">Novo Cliente</a>
        <br>
        <br>
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>Cliente</th>
                <th>Ação</th>
            </tr>
            </thead>

            <tbody>
            @foreach($clients as $client)
            <tr>
                <td>{{ $client->id }}</td>
                <td>{{ $client->user->name }}</td>
                <td>
                    <a href="{{route('admin.clients.edit',['id'=>$client->id])}}" class="btn btn-default btn-small">
                        Editar
                    </a>
                
                    <a href="{{route('admin.clients.destroy',['id'=>$client->id])}}" class="btn btn-default btn-small">
                        Remover
                    </a>
                </td>
            </tr>
            @endforeach
            </tbody>
        </table>

        {!! $clients->render() !!}

    </div>
@endsection